### ISSUE TITLE
possibility to integrated into other plugins?

### ISSUE THREAD

**Issue by joe23rep** [mvllow/modes.nvim#35]
first off- thank you for the plugin. really nicely made and exactly what i needed

now to my request

would it be possible to integrate other plugins into modes?

my specific issue is this:
i dont want to see a cursorline when im in normal mode but want to have it in insert mode.

at first i did that via auto commands which diabled the cursorline in normal mode but with your plugin i basically set the normal mode cursorline color to the background color.

this leads to the same issue i had when i did it via autocommands. i dont have a cursorline in nvim tree

so would it be possible that i set a specific cursorline color for nvim tree with your plugin?

**Comment by fitrh** [comment]
> would it be possible to integrate other plugins into modes?

It is possible, but I don't know if it is worth the complexity


> i dont want to see a cursorline when im in normal mode but want to have it in insert mode.

modes.nvim doesn't have `CursorLine` configuration for normal mode


> at first i did that via auto commands which diabled the cursorline in normal mode but with your plugin i basically set the normal mode cursorline color to the background color.
>
> this leads to the same issue i had when i did it via autocommands. i dont have a cursorline in nvim tree

How does your autocmd look like? For me, since the nvim-tree window sets a specific filetype (`NvimTree`), I would do something like this

```lua
-- after/ftplugin/NvimTree.lua
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#FF0000" })
```

```lua
-- somewhere in yor config, maybe in your nvim-tree config
vim.api.nvim_create_autocmd({ "BufEnter", "WinEnter" }, {
  group = vim.api.nvim_create_augroup("NvimTreeEnter", {}),
  callback = function()
    if vim.bo.filetype == "NvimTree" then
      vim.api.nvim_win_set_option(0, "winhighlight", "CursorLine:NvimTreeCursorLine")
    end
  end,
})

```

Through a quick test, the configuration above works as I understand it from your description, but since I'm not an nvim-tree user, maybe I'm missing something
